### PR TITLE
Implement first part of comment feature 

### PR DESCRIPTION
**Pull request by PrettyPearl2302**
## Description
I implemented the first part of the comment feature, which is getting the comments to be saved in the database. I followed the same format for my user sign up code, so it's pretty similar. I had to store episode data first so that comments could have something to reference when it tries to post into the database, so i created an onClick function for when users click on an episode. 

I still have to implement the react way of monitoring timestamps, then save that together with the comment in my database. I also need advise on how to clear the comment box when the comments get posted : )

## Milestones
TECHNICAL CHALLENGE #1 slayy

## Resources
https://react.dev/reference/react-dom/components/textarea

## Test Plan
Screenshot 2023-07-25 at 11 54 52 AM
Screenshot 2023-07-25 at 11 58 43 AM

### CODE REVIEW

**Review by ssorenson130 — APPROVED** [review]
lgtm!

**Review by ghost — APPROVED** [review]
Looks good. 1 Small suggestion: you may want to handle case when no comment for the episode and show message in comment display area.

**Comment by PrettyPearl2302** [comment]
> Looks good. 1 Small suggestion: you may want to handle case when no comment for the episode and show message in comment display area.

do you mean display some text to say 'no comments yet'?

**Comment by ghost** [comment]
> > Looks good. 1 Small suggestion: you may want to handle case when no comment for the episode and show message in comment display area.
> 
> do you mean display some text to say 'no comments yet'?

Yes that's what I meant

**Pull request merged**
